# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39069b816afa6ebeb09d72ed1336a4f95ad2b0d76c95cebc742c4460ebdc7c823da9cc4beb44e9ea1ce5d52ca568891fe3e1cb0e9ce46e91abcb7adfd2fea217

test:
  secret_key_base: a8cc81c12a136f9480779234fc07e935ab7cf266d703add253d378ae413c13bc06814c3d6ffb4a6553f3714929f285606e9b82afa3f35796d6ebb23cf3726b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
